#!/bin/bash

WARN=50
CRIT=80

MPSTAT=$(mpstat | tail -1 | awk '{print $13}')
CPU=$(echo "100 - $MPSTAT" | bc -l)

echo -e "<span font='FontAwesome'>\uf085</span> ${CPU}%"
echo -e "<span font='FontAwesome'>\uf085</span> ${CPU}%"

if (( $(echo "$CPU >= $CRIT" | bc -l) )); then
    $HOME/bin/i3blocks/colors error
elif (( $(echo "$CPU >= $WARN" | bc -l) )); then
    $HOME/bin/i3blocks/colors warn
fi
