#!/bin/bash

DIR="${BLOCK_INSTANCE:-$HOME}"
WARN=10
CRIT=5

FREE=$(/bin/df -h -P -l "$DIR" | tail -1 | awk '{print $5}' | tr -d %)

echo -e "<span font='FontAwesome'>\uf0a0</span> ${FREE}%"
echo -e "<span font='FontAwesome'>\uf0a0</span> ${FREE}%"

if (( $FREE <= $CRIT )); then
    $HOME/bin/i3blocks/colors error
elif (( $FREE <= $WARN )); then
    $HOME/bin/i3blocks/colors warn
fi
