#!/bin/bash

REPO="/run/media/timothy/BACKUPS"

borg create -v --compression lz4 --stats --progress \
    $REPO::$(hostname)-$(date +%Y-%m-%d)            \
    ~/backups                                       \
    ~/bin                                           \
    ~/books                                         \
    ~/docs                                          \
    ~/dotfiles                                      \
    ~/downloads                                     \
    ~/Dropbox                                       \
    ~/installs                                      \
    ~/pics                                          \
    ~/programming                                   \
    ~/projects                                      \
    ~/sounds                                        \
    ~/vids                                          \
    ~/vm                                            \
    ~/.bash_secrets                                 \
    ~/.dosbox                                       \
    ~/.fonts                                        \
    ~/.gnupg                                        \
    ~/.password-store                               \
    ~/.ssh                                          \
    ~/.wine                                         \
    --exclude '*/.git'                              \
    --exclude ~/Dropbox/.dropbox                    \
    --exclude ~/Dropbox/.dropbox.cache
