#!/bin/bash

# shades
WHITE="97"
LIGHTGRAY="37"
DARKGRAY="90"
BLACK="30"

# regular colors
RED="31"
GREEN="32"
YELLOW="33"
BLUE="34"
PURPLE="35"
CYAN="36"

# light colors
LIGHTRED="91"
LIGHTGREEN="92"
LIGHTYELLOW="93"
LIGHTBLUE="94"
PINK="95"
LIGHTCYAN="96"

ESC="\033["

BOLD="1"
DIM="2"
UNDERLINE="4"

colorize(){
    color=\$${1:-NORMAL}

    echo -ne "${ESC}0;`eval echo $color`m"
    cat
    echo -ne "${ESC}0m"
}

lcolorize(){
    color=\$${1:-NORMAL}

    echo -ne "${ESC}${DIM};`eval echo ${color}`m"
    cat
    echo -ne "${ESC}0m"
}

bcolorize(){
    color=\$${1:-NORMAL}

    echo -ne "${ESC}${BOLD};`eval echo ${color}`m"
    cat
    echo -ne "${ESC}0m"
}

ucolorize(){
    color=\$${1:-NORMAL}

    echo -ne "${ESC}${UNDERLINE};`eval echo ${color}`m"
    cat
    echo -ne "${ESC}0m"
}
