#!/bin/bash

WHOAMI=${SUDO_USER:-$(whoami)}
CONTAINER_DIR="/home/$WHOAMI/.private"
PROFILE_DIR="/home/$WHOAMI/.mozilla/firefox"
SIZE="100M"

if [ "$EUID" -ne 0 ]; then
    PASSWORD="$(zenity --entry --entry-hide-text --title 'sudo' --window-icon "question" --text 'Enter sudo password:')"
    echo "$PASSWORD" | sudo -S $0
    exit
fi


function lockFirefox() {
    umount "$PROFILE_DIR/cryptofox"
    rmdir "$PROFILE_DIR/cryptofox"
    cryptsetup luksClose cryptofox

    if [ $? -eq 0 ]; then
        zenity --info --text "Firefox container locked!"
    else
        zenity --error --text="Could not lock profile!!!"
        return 1
    fi
}

function mountFirefox() {
    # Create mount point if it doesn't exist
    if [ ! -d "$PROFILE_DIR/cryptofox" ]; then
        mkdir -p "$PROFILE_DIR/cryptofox"
        chmod 700 "$PROFILE_DIR/cryptofox"
    fi

    mount -o noatime,nodev,nosuid /dev/mapper/cryptofox "$PROFILE_DIR/cryptofox" || {
        zenity --error --text="Could not mount profile!"
        return 1
    }
}

function startFirefox() {
    sudo -u timothy firefox --no-remote --profile "$PROFILE_DIR/cryptofox"
    trap lockFirefox EXIT
}


if mount | grep $PROFILE_D/cryptofox > /dev/null; then
    zenity --error --text="Profile already mounted, starting Firefox..."
    startFirefox
elif [ ! -f "$CONTAINER_DIR/cryptofox" ]; then
    zenity --question --text "No encrypted profile found! Do you want to create it?"
    answer=$?

    if [ $answer = 0 ]; then
        while [ -z "$PROFILE" ]; do
            cd "$PROFILE_DIR"
            PROFILE=$(ls -d ./*/ | zenity --list --title "Select a Profile" --column "Profile" --separator=" " --multiple) || {
                zenity --error --text="No profile was selected!"
            }
        done

        while [ -z "$PASSWORD" ]; do
            PASSWORD1="$(zenity --entry --entry-hide-text --title 'Encrypt Password' --window-icon 'question' --text 'Password to use for encryption:')"
            PASSWORD2="$(zenity --entry --entry-hide-text --title='Confirm Password' --window-icon 'question' --text 'Confirm password:')"

            if [ "$PASSWORD1" = "$PASSWORD2" ]; then
                PASSWORD=$PASSWORD1
            else
                zenity --error --text="Passwords did not match!"
            fi
        done


        if [ ! -d "$CONTAINER_DIR" ]; then
            mkdir -p "$CONTAINER_DIR"
            chmod 700 "$CONTAINER_DIR"
        fi

        truncate -s "$SIZE" "$CONTAINER_DIR/cryptofox"
        chmod 600 "$CONTAINER_DIR/cryptofox"

        # Encrypt and open container
        echo -n $PASSWORD | cryptsetup --key-file "-" luksFormat "$CONTAINER_DIR/cryptofox"
        echo -n $PASSWORD | cryptsetup --key-file "-" luksOpen "$CONTAINER_DIR/cryptofox" cryptofox

        # Make the filesystem
        mkfs.ext2 /dev/mapper/cryptofox
        tune2fs -m 0 /dev/mapper/cryptofox

        mountFirefox || exit 1
        chown $WHOAMI "$PROFILE_DIR/cryptofox"

        cp -R "$PROFILE_DIR/$PROFILE/"* "$PROFILE_DIR/cryptofox"

        startFirefox
    else
        zenity --error --text="Encrypted profile doesn't exist!"
        exit 1
    fi
else
    PASSWORD=""$(zenity --entry --entry-hide-text --title 'Decrypt Password' --window-icon "question" --text 'Password for decryption:')""

    echo -n $PASSWORD | cryptsetup --key-file "-" luksOpen "$CONTAINER_DIR/cryptofox" cryptofox || {
        zenity --error --text="Could not decrypt profile!"
        exit 1
    }

    mountFirefox || exit 1
    startFirefox
fi
