#!/bin/bash

usage () {
cat <<HELP
Wrapper for GPG symmetric encryption

Encrypt files or directories using AES256 or automatically
decrypt a file created with this utility (files have an ".enc" extension)


https://github.com/keithieopia/bin/

Copyright (c) 2016 Timothy Keith
Licensed under the MIT license.
HELP
}

if [ -z "$1" ]; then
    echo -e "\e[31mYou must specify something to encrypt!\e[39m"
    exit 1
elif [ "$1" == "-h" ]; then
    usage
    exit
fi


if [ -d "$*" ]; then
    echo -e "\033[1;32mEncrypting directory...\033[0m"

    NAME=$(basename $*)
    tar -c --xz "$*" | gpg --output "$NAME.txz.enc" --symmetric --cipher-algo AES256

else

    if [ -f "$*" ]; then

        FILE="$*"

        if [[ ${FILE: -8} == ".txz.enc" ]]; then
            echo -e "\033[1;32mDecrypting directory...\033[0m"

            gpg2 --decrypt $FILE | tar -xJf -

        elif [[ ${FILE: -4} == ".enc" ]]; then
            echo -e "\033[1;32mDecrypting file...\033[0m"

            NAME=$(basename $FILE .enc)
            gpg2 --output $NAME --decrypt $FILE

        else
            echo -e "\033[1;32mEncrypting file...\033[0m"

            gpg2 --output $FILE.enc --symmetric --cipher-algo AES256 $FILE
        fi
    else
        echo -e "\e[31mThat file does not exist!\e[39m"
        exit 1
    fi
fi
