#!/bin/bash

usage () {
cat <<HELP 
Create folders and files expected to be in ~/.cache normally

Usage: $(basename "$0")
   -d : Print debug information


https://github.com/keithieopia/bin/
    
Copyright (c) 2016 Timothy Keith
Licensed under the BSD 2-clause license.
HELP
}

colorize () {
    SUCCESS="0;32"
    WARN="0;33"
    ESC="\033["

    COLOR=\$${1:-NORMAL}
        
    echo -ne "${ESC}`eval echo ${COLOR}`m"
    cat
    echo -ne "${ESC}0m"
}


while [ "$1" != "" ]; do
case $1 in
    -d )
        DEBUG=1
        ;;
    -h )
        usage
        exit
        ;;
esac
shift
done

if mount | grep "tmpfs on $HOME/.cache" > /dev/null; then
    if [ ! -f "$HOME/.cache/.lock" ]; then

        mkdir "$HOME/.cache/thumbnails"
        mkdir "$HOME/.cache/flash"

        # Create lockfile used to test if .cache has been populated yet
        touch "$HOME/.cache/.lock"
        [ $DEBUG == "1" ] && echo "~/.cache setup!" | colorize SUCCESS
    exit
    else
        [ $DEBUG == "1" ] && echo "~/.cache already setup, nothing to do..." | colorize WARN
        exit
    fi
else
    [ $DEBUG == "1" ] && echo "~/.cache is not mounted as tmpfs, nothing to do..." | colorize WARN
    exit 
fi
