#!/bin/bash

if mount | grep "tmpfs on $HOME/.cache" > /dev/null; then
    if [ ! -f "$HOME/.cache/.lock" ]; then

        mkdir "$HOME/.cache/thumbnails"
        mkdir "$HOME/.cache/flash"

        # Create lockfile used to test if .cache has been populated yet
        touch "$HOME/.cache/.lock"
    fi
else
    echo "~/.cache is not mounted as tmpfs, nothing to do..." | colorize RED
fi
