#!/bin/bash

##
## Remove fluff
##
pacman -Rns xfsprogs reiserfsprogs pcmciautils vi jfsutils mdadm lynx

##
## Install universal packages
##
pacman -S sudo git bash-completion zip htop wget ufw unrar p7zip unzip sqlite \
reflector pydf php php-gd php-sqlite dcfldd curl cronie colord colordiff rsync

##
## Enable services
##
systemctl enable ufw cronie
systemctl start ufw cronie
ufw enable

##
## Setup sudo
##
cat >> /etc/sudoers << EOF
%wheel ALL=(ALL) ALL
EOF

##
## Setup user
##
useradd -m -g users -G wheel -s /bin/bash timothy
passwd timothy
su timothy
cd ~

##
## Install personal files
##
git clone https://github.com/keithieopia/bin.git
git clone https://github.com/keithieopia/dotfiles.git

##
## Enable personal file configs
##
rm /etc/issue
ln -s ~/dotfiles/issue /etc/issue
rm ~/.bash_logout
ln -s ~/dotfiles/.bash_logout ~/.bash_logout
rm ~/.bash_profile
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
rm ~/.bashrc
ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.bash_aliases ~/.bash_aliases
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.nanorc ~/.nanorc
rm /etc/cron.monthly
ln -s ~/dotfiles/cron.monthly /etc/cron.monthly

##
## Setup Unbound
##
pacman -S unbound openresolv
rm /etc/openresolv.conf
ln -s ~/dotfiles/openresolv.conf /etc/openresolv.conf
resolvconf -u
ln -s ~/dotfiles/unbound/unbound.conf /etc/unbound/unbound.conf
ln -s ~/dotfiles/unbound/blocklist-mine.conf /etc/unbound/blocklist-mine.conf
unbound-control-setup
sh /etc/cron.monthly/unbound-root-hints
sh /etc/cron.monthly/unbound-someonewhocares-block
sh /etc/cron.monthly/unbound-yoyo-block
systemctl enable unbound

##
## Install packer
##
pacman -S expac jshon
mkdir packer
cd packer
wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=packer PKGBUILD
makepkg
pacman -U packer-*
cd ..
rm -rf packer

##
## Setup SSH
##
pacman -S openssh fail2ban
systemctl enable sshd fail2ban
ufw allow 22/tcp

ln -s ~/dotfiles/issue.net /etc/issue.net

cat >> /etc/ssh/sshd_config << EOF
Banner /etc/issue.net
PermitRootLogin no
LoginGraceTime 30
ClientAliveInterval 600
ClientAliveCountMax 0
EOF

systemctl start sshd fail2ban
systemctl restart ufw

##
## Laptop Only!
###############################################################################

##
## Install laptop only packages
##
pacman -S acpi adwaita-icon-theme alsa-plugins alsa-utils aspell zenity cabextract \
xorg-xkill xf86-input-keyboard xf86-input-synaptics libva-intel-driver libva-mesa-driver
jre8-openjdk jdk8-openjdk jre8-openjdk-headless iw hspell haveged hicolor-icon-theme \
gimp geany geany-plugins xdg-user-dirs xarchiver wpa_actiond wpa_supplicant \
vlc oblogout ntfs-3g mpg123 mesa openbox thunar sqliteman scrot sakura tumbler \
pypanel ffmpegthumbnailer feh eog evince chromium xorg-xinit

# Firefox
pacman -S firefox flashplugin hunspell hunspell-en

# Fonts: indic -> look of disapproval, symbola -> emoji
pacman -S ttf-dejavu ttf-bitstream-vera ttf-droid ttf-indic-otf ttf-symbola

# Wine
pacman -S wine wine-mono wine_gecko winetricks lib32-alsa-lib lib32-alsa-plugins \
lib32-mesa lib32-mesa-libgl lib32-mpg123

packer -S systemd-readahead geany-themes-git dropbox obmenu-generator pysystray-git \
pavumeter perl-linux-desktop-files tixati


##
## Enable laptop packages
##
sudo systemctl enable systemd-readahead-collect systemd-readahead-replay haveged \
netctl-auto@wlp1s0 netctl-ifplugd@enp1s0


##
## Enable laptop configs
##
mkdir ~/.config
ln -s ~/dotfiles/.pypanelrc ~/.pypanelrc
ln -s ~/dotfiles/.xinitrc ~/.xinitrc
ln -s ~/dotfiles/openbox ~/.config/openbox
ln -s ~/dotfiles/user-dirs.dirs ~/.config/user-dirs.dirs
ln -s ~/dotfiles/dunst ~/.config/dunst
ln -s ~/dotfiles/mozilla/mozilla.cfg /usr/lib/firefox/mozilla.cfg
ln -s ~/dotfiles/mozilla/local-settings.js /usr/lib/firefox/defaults/pref/local-settings.js

##
## Setup RAM disk for ~/.cache
##
rm -rf ~/.cache
mkdir ~/.cache
echo "tmpfs   /home/timothy/.cache   tmpfs   noatime,nodev,nosuid,size=1G   0 0" >> /etc/fstab
mount ~/.cache

##
## Link similar directories together
##
mkdir ~/.adobe
ln -s ~/.adobe ~/.macromedia
mkdir ~/.cache/thumbnails
ln -s ~/.cache/thumbnails ~/.thumbnails
