#!/bin/bash

IFS=$'\n';

for file in `find . -type f`
do

    echo "Looking at $file..." | colorize BOLDWHITE

    base=${file%.*}
    ext=${file##*.}
    lowercase=$base.${ext,,}
    dashed=${lowercase// /-}

    if [ "$lowercase" != "$file" ]; then
        echo "Converting file's extension to lowercase" | colorize BLUE
        mv "$file" "$lowercase"
        file=$lowercase
    fi
    
    if 
        echo "Converting spaces in filename to dashes" | colorize BLUE
        mv "$file" "$lowercase"
    fi

    case $file in
        *.png)
            echo "Optimizing as PNG: $file..." | colorize BLUE
            optipng -o7  -strip all "$file"
            ;;

        *.jpg|*.jpeg)
            echo "Optimizing as JPEG: $file..." | colorize BLUE
            jpegoptim --strip-all "$file"
            cp "$file" "$base-backup.bak"
            jpegoptim -m80 "$file"
            echo "Since image was optimized using lossy compression, you should " \
                 "make sure the quality isn't terrible. A backup has been automatically " \
                 "made to this end." | colorize YELLOW
            ;;

        *.gif)
            echo "Optimizing as GIF: $file..." | colorize BLUE

            if [[ ! identify -format "%[fx:n>1]\n" "$file" | grep -q 1 ]]; then
                echo "GIF isn't animated! Consider converting it to a PNG as " \
                     "optimized PNGs are almost allows smaller than GIFs" | colorize YELLOW
            fi

            gifsicle -03 --no-extensions < "$file" > $file
            ;;
        *)
            echo "Not a recognized image!" | colorize RED
            ;;
    esac

    echo -e "\n\n"
done

exit
