#!/bin/bash

case "$1" in
    "alert")     SOUND="buzz.ogg"           ;;
    "critpower") SOUND="power-off.ogg"      ;;
    "error")     SOUND="squish.ogg"         ;;
    "info")      SOUND="info.ogg"           ;;
    "logout")    SOUND="battle-control.ogg" ;;
    "lowpower")  SOUND="power-low.ogg"      ;;
    "startup")   SOUND="psx.ogg"            ;;
    "volume")    SOUND="heal.ogg"           ;;
    *)           SOUND="pop.ogg"            ;;
esac

paplay "$HOME/bin/sounds/$SOUND"
