#!/bin/bash

usage () {
cat <<HELP 
Plays a tune depending on a option, useful for 'dunst'

usage: $(basename "$0") [OPTION]

   alert     : Play to get attention  
   critpower : Play on very low power    
   error     : Play for errors  
   info      : Play for informational notices  
   logout    : Play on logout  
   lowpower  : Play for low power notifications  
   startup   : Startup sound  
   volume    : Play on volume changes  
 

https://github.com/keithieopia/bin/
    
Copyright (c) 2016 Timothy Keith
Licensed under the MIT license.
HELP
}

case "$1" in
    "alert")     SOUND="buzz.ogg"           ;;
    "critpower") SOUND="power-off.ogg"      ;;
    "error")     SOUND="squish.ogg"         ;;
    "info")      SOUND="info.ogg"           ;;
    "logout")    SOUND="battle-control.ogg" ;;
    "lowpower")  SOUND="power-low.ogg"      ;;
    "startup")   SOUND="psx.ogg"            ;;
    "volume")    SOUND="heal.ogg"           ;;
    "-h")        usage; exit                ;;
    *)           SOUND="pop.ogg"            ;;
esac

have() { type "$1" &> /dev/null; }
have paplay && paplay "$HOME/bin/sounds/$SOUND" || {
    echo "$0 requires 'libpulse' to be installed!"
    exit 1
}
