#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo -e "\e[33mThis script must be run as root, recalling self with sudo...\e[39m"
    sudo $0 $*
    exit 0
fi

if [ ! -f /mnt/private/$1.img ]; then
    echo -e "\e[31m$1.img does not exist\e[39m"
    exit 1
fi

if mount | grep /home/$SUDO_USER/Private/$1 > /dev/null; then
    echo -e "\e[34mEncrypted container already unlocked, closing...\e[39m"
    umount /home/$SUDO_USER/Private/$1
    cryptsetup luksClose $1
    echo -e "\e[32m$1 successfully closed!\e[39m"
    exit 0
else
    if [ ! -d /home/$SUDO_USER/Private/$1 ]; then
        echo -e "\e[33mMount point does not exist, creating it...\e[39m"
        mkdir -p /home/$SUDO_USER/Private/$1
    fi

    echo -e "\e[34mUnlocking encrypted container...\e[39m"
    cryptsetup luksOpen /mnt/private/$1.img $1

    echo -e "\e[34mMounting container...\e[39m"
    mount -o noatime,nodev,nosuid /dev/mapper/$1 /home/$SUDO_USER/Private/$1

    if [ $DISPLAY ]; then
        echo -e "\e[34mI noticed you are in Xorg, starting thunar for you...\e[39m"
        su $SUDO_USER -c "thunar /home/$SUDO_USER/Private/$1" &
    fi

    echo -e "\e[32m$1 successfully opened!\e[39m"
    exit 0
fi
