#!/bin/bash

read -r -d '' QUOTES <<'EOF'
Confidence is not "They will like me". Confidence is "I'll be fine if they
don't"
-- Anonymous

Don't look for someone who will solve your problems. Look for someone who will
face them with you
-- Anonymous

Only a fool ignores the truth because he doesn't lke the messenger
-- Anonymous

A certain amount of opposition is a help, not a hindrance. Kites rise against
the wind, not with it
-- Anonymous

Our lives begin to end the day we become silent about things that matter
-- Martin Luther King, Jr.

Resentment is like drinking poison and expecting it to kill your enemies
-- Nelson Mandela

Many of life's failures are people who did not realize how close they were to
success when they gave up
-- Thomas Edison

Be who you are, say what you mean because those who mind don't matter and those
who matter don't mind
-- Dr. Seuss

These mountains that you are carrying, you were only suppose to climb
-- Najwa Zebian

The thing with broken clocks is you can always tell exactly when they stopped
ticking, with people it isn't so easy and sometimes you can't even tell they're
broken
-- Anonymous

If someone does not want me it is not the end of the world, but if I do not want
me, the world is nothing but endings
-- Nayyirah Waheed, "salt."

Where you are is not who you are
-- Nayyirah Waheed, "salt."

The power of accurate observation is often called cynicism by those who have not
got it.
-- George Bernard Shaw

Everyone you meet has a part to play in our story. And while some may take a
chapter, others a paragraph, and most will be no more than scribbled notes in
the margins, someday, you'll meet someone who will become so integral to your
life, you'll put their name in the title.
-- Beau Taplin

Be brave, my darling, you have faced dark times before and you're still here
-- Chris Lees

Your rights matter because you never know when you're going to need them.
-- Edward Snowden

No monumental evil act in the history of mankind has been committed by anyone
who thought of themselves as "evil" — on the contrary, the worse the (objective)
evil, the more the perpetrator was completely convinced of the goodness of
himself and of his "purification"
-— Eric Naggum

When students cheat on exams it's because our school system values grades more
than students value learning.
-― Neil deGrasse Tyson

They always say time changes things, but you actually have to change them
yourself
-— Andy Warhol

The man who fears suffering is already suffering from what he fears
-— Michel de Montaigne

Security is mostly a superstition. Avoiding danger is no safer in the long run
than outright exposure. Life is either a daring adventure, or nothing
-— Helen Keller

A superior pilot uses his superior judgment to avoid having to exercise his
superior skill
-— Frank Borman

The opposite of courage is not cowardice, it's conformity
-— John Perry Barlow

The reasonable man adapts himself to the world. The unreasonable man persists in
trying to adapt the world to himself. All progress, therefore, depends upon the
unreasonable man
-— George Bernard Shaw

The trouble with the world is that the stupid are cocksure and the intelligent
full of doubt.
-— Bertrand Russell

Only the mediocre are always at their best.
-— Jean Giraudoux

It takes considerable knowledge just to realize the extent of your own ignorance
-— Thomas Sowell

I think if we ban certain religions, if we censor the Internet, I think that at
that point the terrorists will have won.
-- Rand Paul

The individual has always had to struggle to keep from being overwhelmed by the
tribe. If you try it, you will be lonely often, and sometimes frightened. But no
price is too high to pay for the privilege of owning yourself.
-— Friedrich Nietzsche

If you could kick the person in the pants responsible for most of your trouble,
you wouldn't sit for a month
-- Theodore Roosevelt

If you don't know where you are going, every road will get you nowhere
-— Henry Kissinger

I choose a lazy person to do a hard job. Because a lazy person will find an easy
way to do it
-- Bill Gates

Offending people is a necessary and healthy act. Every time you say something
that's offensive to another person you just caused a discussion. You just forced
them to have to think
-— Louis Székely

When you're young, you look at television and think, There’s a conspiracy. The
networks have conspired to dumb us down. But when you get a little older, you
realize that’s not true. The networks are in business to give people exactly
what they want. That’s a far more depressing thought.
-— Steve Jobs

Be kind, for everyone is fighting a hard battle
-— Ian MacLaren

Morality is doing what’s right regardless of what you’re told. Obedience is
doing what you’re told regardless of what is right
-- Anonymous

Eventually, I decided that thinking was not getting me very far and it was time
to try building
-— Rob Pike

One is never so dangerous as when he’s utterly convinced he is right
-— John Perry Barlow

Too often we enjoy the comfort of opinion without the discomfort of thought
-– John F. Kennedy

Change is the law of life and those who look only to the past or present are 
certain to miss the future.
-- John F. Kennedy

The future is always scary to those who cling to the past
-— Tim O'Reilly

If you think you are too small to make a difference, try sleeping with a
mosquito
-- The Dalai Lama

Share your knowledge. It's a way to achieve immortality
-— The Dalai Lama

Perfection is achieved, not when there is nothing more to add, but when there is
nothing left to take away
-— Antoine-Marie-Roger de Saint-Exupery, "Wind, Sand and Stars"

Distrust those in whom the desire to punish is strong
-— Johann Wolfgang von Goethe

Sometimes you will never know the value of something, until it becomes a memory.
-― Dr. Seuss

One of the greatest regrets in life is being what others would want you to be,
rather than being yourself.
―- Shannon L. Alder

Nothing strengthens authority so much as silence.
-― Leonardo da Vinci

I believe there are more instances of the abridgment of the freedom of the
people by gradual and silent encroachments of those in power than by violent and
sudden usurpations.
-― James Madison

No dream is guaranteed, the grace of age is when we learn to accept
-- Farscape, "Crichton Kicks"

Nothing adds excitement like something that is none of your business
-- Anonymous

A dog is carrying a bone, and comes to a stream where it sees it's own
reflection. Mistaking it for a dog with a better bone, it barks, hoping the
"other" dog will drop it's bone. But in doing so, the dog drops it's own bone,
where it sinks to the bottom of the water. If the dog is smart enough to learn,
if it could have had only one bone, which would it have wanted?
-- Aesop's Fables, "The Dog and its Reflection"

Everyone is in favor of free speech. Hardly a day passes without its being
extolled, but some people's idea of it is that they are free to say what they 
like, but if anyone else says anything back, that is an outrage.
― Winston Churchill
EOF


# Hackish trickery to get shuf to pick a group seperated "\n\n" (an empty line)
# instead of the default "\n" (new line) as a element seperator.
#
# sed is mixed with tr, because tr searches by char not a complete string
# You could probably just use sed, but I doubt it would be very readable.
RAND_QUOTE=$(tr "\n" "\r" <<< "$QUOTES" | sed 's/\r\r/\n/g' | shuf -n1 | tr "\r" "\n")


# Last line is always the author, so split it off so it can be pretty printed
# Otherwise, you could just echo $RAND_QUOTE if you care more about speed vs formatting
head -n -1 <<< "$RAND_QUOTE"

echo -ne "\t"
tail -1 <<< "$RAND_QUOTE"
