#!/bin/bash

usage () {
cat <<HELP 
Locks the screen with a neat pixelated effect

Usage: $(basename "$0")


https://github.com/keithieopia/bin/
    
Copyright (c) 2016 Timothy Keith
Licensed under the BSD 2-clause license.
HELP
}

if [ "$1" == "-h" ]; then
    usage
    exit
fi

have() { type "$1" &> /dev/null; }
if ! have i3lock; then
    echo "$0 requires 'i3lock' to be installed!"
    exit 1
fi
if ! have scrot; then
    echo "$0 requires 'scrot' to be installed!"
    exit 1
fi
if ! have convert; then
    echo "$0 requires 'imagemagick' to be installed!"
    exit 1
fi

scrot /tmp/screenlock.png
convert /tmp/screenlock.png -scale 5% -scale 2000% /tmp/screenlock.png
i3lock -f -e -i /tmp/screenlock.png
