#!/bin/bash

scrot /tmp/screenlock.png
#mogrify -scale 10% -scale 1000% /tmp/screenlock.png
convert /tmp/screenlock.png -scale 5% -scale 2000% /tmp/screenlock.png


i3lock -f -e -i /tmp/screenlock.png

sleep 300; pgrep i3lock && xset dpms force off
