#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    if [ -z "$SUDO_COMMAND" ]; then
        echo -e "\e[33mThis script must be run as root, recalling self with sudo...\e[39m"
        sudo $0 $*
        exit 0
    else
        echo -e "\e[31mThis script must be run as root\e[39m"
        exit 1
    fi
fi

echo 'Shredding slack space...'
cd /home
dcfldd if=/dev/urandom of=fill bs=4092
echo 'Shredding complete, removing slack file...'
sync
rm fill
sync
echo 'Slack space successfully shredded.'
