#!/bin/bash

logsDir="/home/keithieopia/logs/frontend/"
backupDir="/home/keithieopia/backups/"
backupApps=(atvpartsconnection calvertpipeband cvrcorp honestpcrepair keithieopia kerriandtimothy myoldfamilyphotos ooocc piwik)
today="$(date -I)"
emailFrom="no-reply@honestpcrepair.com"
emailTo="timothy@keithieopia.com"
emailSubject="Backups for ${today}"
emailBody="Attached is a gzipped tarball of access and error logs from the web server for ${today}"

if [[ -d ${backupDir}${today} ]]; then
	echo "ERROR: Backup directory already exists."
	exit
else
	mkdir ${backupDir}${today}
fi

for app in "${backupApps[@]}"; do
	logFiles=("access_${app}" "access_${app}_php" "error_${app}" "error_${app}_php")

	for logFile in "${logFiles[@]}"; do
		for i in {0..7}; do
			filename=${logsDir}${logFile}.log
			if [[ $i -gt 0 ]]; then
				filename+=".$i"
			fi

			if [ -f "${filename}" -a -s "${filename}" ]; then
				cp ${filename} ${backupDir}${today}
			fi
		done
	done
done

cd ${backupDir}${today}
tar zcvf "../${today}.tgz" .
rm *.log*
cd ..
rmdir ${today}

echo "${emailBody}" | mutt -a "${today}.tgz" -s "${emailSubject}" -- ${emailTo}
