#!/bin/bash

function hr() {
	printf '%46s\n' | tr ' ' -
}

function center() {
	C=$(tput cols)

	while IFS= read -r line; do
		printf "%$(((C+${#line})/2))s\n" "$line"
	done
}


function motd() {
	DATE=$(date '+%Y-%m-%d @ %-I:%M %p')

	PKG=$(apt-get --just-print upgrade | grep Inst | wc -l)
	SECPKG=$(apt-get --just-print upgrade | grep Inst | grep Debian-Security | wc -l)
	MISCPKG=$(echo "$PKG - $SECPKG" | bc -l)

	LOAD=$(iostat | sed -n 4p | awk '{load=100-$6; print load "%"}')
	SWAP=$(free | grep Swap: | awk '{printf("%.2f%%\n", $3/$2*100)}')
	MEM=$(free | grep Mem: | awk '{printf("%.2f%%\n", $3/$2*100)}')

	ROOT=$(df / | tail -1 | awk '{print $5}')
	HOME=$(df /home | tail -1 | awk '{print $5}')

	tput setaf 6
	if hash figlet 2>/dev/null; then
		figlet -c $(hostname)
	else
		echo $(hostname) | tr '[:lower:]' '[:upper:]'
	fi
	tput sgr0

	echo "$DATE" | center

	tput setaf 6
	hr | center

	{
		# column breaks on tput color codes
		# instead use awk to right pad with set number of spaces
		#echo -e "$(tput setaf 6)CPU|MEM|SWAP|ROOT|HOME$(tput sgr0)\n${LOAD}|${MEM}|${SWAP}|${ROOT}|${HOME}" | column -t -c 5 -s"|"
		echo CPU  | awk '{printf ("%-10s%s", $1, "")}'
		echo MEM  | awk '{printf ("%-10s%s", $1, "")}'
		echo SWAP | awk '{printf ("%-10s%s", $1, "")}'
		echo ROOT | awk '{printf ("%-10s%s", $1, "")}'
		echo HOME | awk '{printf ("%-4s%s", $1, "")}'
		echo
	} | center
	tput sgr0

	{
		echo $LOAD  | awk '{printf ("%-10s%s", $1, "")}'
		echo $MEM  | awk '{printf ("%-10s%s", $1, "")}'
		echo $SWAP | awk '{printf ("%-10s%s", $1, "")}'
		echo $ROOT | awk '{printf ("%-10s%s", $1, "")}'
		echo $HOME | awk '{printf ("%-4s%s", $1, "")}'
		echo
	} | center

	tput setaf 6
	hr | center
	tput sgr0

    # newline
	echo

	{
		if [[ "$PKG" -eq "0" ]]; then
			echo "System is up-to-date"
		else
			if [[ "$SECPKG" -gt "0" && "$MISCPKG" -gt "0" ]]; then
				echo "$SECPKG security and $MISCPKG misc. updates are ready for install"
			elif [[ "$MISCPKG" -gt "0" ]]; then
				echo "$MISCPKG misc. updates are ready for install"
			else
				echo "$SECPKG security updates are ready for install"
			fi
		fi
	} | center

    # trailing newline
    echo
}

motd > /etc/motd

