#!/bin/bash

# update db after x seconds old,
# default is 86400 or one day
UPDATE_AFTER=86400

# parse log for last update, then convert it to a timestamp
LAST_DATE=$(grep "synchronizing package lists" /var/log/pacman.log | tail -1 | cut -d "[" -f2 | cut -d "]" -f1)
LAST_TS=$(date -d "$UPDATE_DATE" +%s)

# get current timestamp
CURRENT_TS=$(date +%s)

if ((CURRENT_TS-LAST_TS > UPDATE_AFTER)); then
    
    # update the db or die if it fails
    # you'll want to setup a NOPASSWD sudo entry
    if ! sudo pacman -Sy &> /dev/null; then
        echo "DB OUTDATED"
        exit
    fi
fi

# list the number of updates available
NUM_UPDATES=$(pacman -Qu | wc -l)

if ((NUM_UPDATES > 0)); then
    echo "$NUM_UPDATES pkgs"
else
    echo "up to date"
fi
