#!/bin/bash

BATTERY="$(cat /sys/class/power_supply/BAT1/capacity)"
STATUS="$(cat /sys/class/power_supply/BAT1/status)"


if [ "$STATUS" == "Charging" ]; then
    echo -n "$BATTERY%"
    echo -n "+"
elif [ "$STATUS" == "Discharging" ]; then
    echo -n "$BATTERY%"
    echo -n "-"
else
    echo -n "$BATTERY%"
fi
