#!/bin/bash

ACTIVE=$(bspc config focused_border_color)
INACTIVE=$(bspc config active_border_color)

DESKTOPS=$(bspc query -T -m | jshon -e desktops -a -e name -u)
CURRENT=$(bspc query -T -d | jshon -e name -u)

while read -r desktop; do
    if [[ "$desktop" == "$CURRENT" ]]; then
    
        echo -n "%{F$ACTIVE}$desktop%{F-} "
    else
        echo -n "%{A:bspc desktop -f $desktop:}"
        echo -n "%{F$INACTIVE}$desktop%{F-}"
        echo -n "%{A} "
    fi
done <<< "$DESKTOPS"
