#!/bin/bash

VOLUME=$(awk '/%/ {gsub(/[\[%\]]/,""); print $4}' <(amixer sget Master) | head -1)

if $(amixer -D pulse get Master | tail -1 | grep off > /dev/null); then
    echo -n "mute"
else
    echo -n "$VOLUME%"
fi
