#!/bin/bash

usage () {
cat <<HELP
Create folders and files expected to be in ~/.cache normally


https://github.com/keithieopia/bin/

Copyright (c) 2016 - 2018 Timothy Keith
Licensed under the MIT license.
HELP
}

if [ "$1" == "-h" ]; then
	usage
	exit
fi

rm -rf "/dev/shm/${USER}-cache"
mkdir "/dev/shm/${USER}-cache"
chmod 700 "/dev/shm/${USER}-cache"

if [ ! -L "$HOME/.cache" ]; then
    echo "$HOME/.cache not symlinked to /dev/shm yet..."

    if [ -d "$HOME/.cache" ]; then
        if [ -z "$(ls -A /home/${USER}/.cache)" ]; then
            echo "$HOME/.cache not empty, cowardly refusing to rm -rf it..."
            exit 1
        fi

        rm -rf "/home/${USER}/.cache"
    fi

    ln -s "/dev/shm/${USER}-cache" "/home/${USER}/.cache"
fi

if [ ! -d "$HOME/.cache/thumbnails" ]; then
    mkdir "$HOME/.cache/thumbnails"
fi

if [ ! -L "$HOME/.thumbnails" ]; then
	if [ -d "$HOME/.thumbnails" ]; then
		rm -r "$HOME/.thumbnails"
	fi

   	ln -s "$HOME/.cache/thumbnails" "$HOME/.thumbnails"
fi

