#!/bin/bash

if ! [ $(id -u) = 0 ]; then
    echo "This script must run as root!"
    exit 1
fi

if ! [ -f "/etc/lsyncd/lsync.conf.lua" ]; then
    cd /home/timothy/dotfiles
    stow -t / lsyncd

    mkdir -p /var/log/lsyncd
    touch /var/log/lsyncd/lsyncd.{log,status}
fi

# provides $HOME_GATEWAY value
source /home/timothy/.bash_secrets

GATEWAY=$(ip neigh | grep $(ip route show match 0/0 | awk '{print $3}') | awk '{print $5 }')

if [ "$GATEWAY" = "$HOME_GATEWAY" ]; then
    service lsyncd start
fi
