#!/bin/bash

#VOLUME="$(amixer -D pulse get Master | tail -1)"
PA=$(pactl list sinks)
VOLUME=$(grep '^[[:space:]]Volume:' <<< "$PA" | awk '{print $5}')

if grep -q 'Mute: no' <<< "$PA"; then
    ICON="\uf028"
else
    ICON="\uf026"
fi

echo -e "<span font='FontAwesome'>$ICON</span> $VOLUME"
echo -e "<span font='FontAwesome'>$ICON</span> $VOLUME"
