#!/bin/bash

colorize () {
    SUCCESS="0;32"
    WARN="0;33"
    ERROR="0;31"
    ESC="\033["

    COLOR=\$${1:-NORMAL}

    echo -ne "${ESC}`eval echo ${COLOR}`m"
    cat
    echo -ne "${ESC}0m"
}

run () {
    if pgrep "$1" > /dev/null; then
        echo "$1 already running, skipping..." | colorize WARN
    else
        echo "Starting $1..." | colorize SUCCESS
        exec $@ &>/dev/null
    fi
}

# Wait a maximum of one minute for network connectivity 
# then die if we don't get it 
ROUTE=$(ip route show match 0/0)

n=0
while [ -z "$ROUTE" ]; do
    n=$[$n+1]
    
    if [ $n -ge 6 ]; then
        echo "No network connectivity after 1 minute!" | colorize ERROR
        exit 1
    else
        echo "No network connectivity, sleeping..." | colorize WARN
        sleep 10
        ROUTE=$(ip route show match 0/0)
    fi
done

run dropbox
run aarchup -l 360 # notify of updates every 6 hours