#!/bin/bash

usage () {
cat <<HELP 
Locks the screen with a neat pixelated effect

Usage: $(basename "$0")


https://github.com/keithieopia/bin/
    
Copyright (c) 2016 Timothy Keith
Licensed under the BSD 2-clause license.
HELP
}

if [ "$1" == "-h" ]; then
    usage
    exit
fi

have() { type "$1" &> /dev/null; }
if ! have i3lock; then
    echo "$0 requires 'i3lock' to be installed!"
    exit 1
fi
if ! have scrot; then
    echo "$0 requires 'scrot' to be installed!"
    exit 1
fi
if ! have convert; then
    echo "$0 requires 'imagemagick' to be installed!"
    exit 1
fi

scrot /tmp/screenlock.png

# Neat pixilated blur
#convert /tmp/screenlock.png -scale 5% -scale 2000% /tmp/screenlock.png        

# slow blur
#convert /tmp/screenlock.png -blur 0x8 /tmp/screenlock.png

# Faster blur
convert /tmp/screenlock.png -filter Gaussian -resize 50% -define filter:sigma=2.5 -resize 200% /tmp/screenlock.png 

# Hackers can't break in if you use Deputy Barney Fife Protection
composite -gravity center -gravity south ~/bin/wm/lockscreen/barney-fife.png /tmp/screenlock.png /tmp/screenlock.png

paplay ~/bin/sounds/battle-control.ogg &

i3lock -f -e -i /tmp/screenlock.png
