#! /bin/sh

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d term web code media float

# Open apps on a certain desktop
bspc rule -a Firefox desktop=^2
bspc rule -a Gimp desktop=^4 state=floating follow=on
bspc rule -a VLC desktop=^4 state=floating


# colors
bspc config normal_border_color  "#111111" # Black
bspc config active_border_color  "#252525" # Black
bspc config focused_border_color "#15A88B" # Teal

# Prevent lemonbar from being covered
bspc rule -a lemonbar layer=above manage=on border=off

# padding for lemonbar
bspc config bottom_padding 20

# autostart
sxhkd &
~/bin/wm/floating-desktop &
~/bin/wm/lemonade &
