#!/bin/bash
WARN=25
CRIT=10
PERCENT=$(< /sys/class/power_supply/BAT1/capacity)

if [ "$(< /sys/class/power_supply/BAT1/status)" == "Discharging" ]; then
    if (( $PERCENT > 80 )); then
        ICON="\uf240"
    elif (( $PERCENT > 60 )); then
        ICON="\uf241"
    elif (( $PERCENT > 40 )); then
        ICON="\uf242"
    elif (( $PERCENT > 20 )); then
        ICON="\uf243"
    else
        ICON="\uf244"
    fi
else
    ICON="\uf1e6"
fi

echo -e "<span font='FontAwesome'>$ICON</span> ${PERCENT}%"
echo -e "<span font='FontAwesome'>$ICON</span> ${PERCENT}%"

if (( $PERCENT <= $CRIT )); then
    $HOME/bin/x11/i3blocks/colors error
elif (( $PERCENT <= $WARN )); then
    $HOME/bin/x11/i3blocks/colors warn
fi
