#!/bin/bash

WARN=50
CRIT=80

MPSTAT=$(mpstat | tail -1 | awk '{print $13}')
CPU=$(echo "c=100 - $MPSTAT; if (c < 1) print 0; c" | bc -l)

echo -e "${CPU}%"
echo -e "${CPU}%"

if (( $(echo "$CPU >= $CRIT" | bc -l) )); then
    $HOME/bin/i3blocks/colors error
elif (( $(echo "$CPU >= $WARN" | bc -l) )); then
    $HOME/bin/i3blocks/colors warn
fi
