#!/bin/bash

change_gnome_wallpaper() {
    gsettings set org.gnome.desktop.background picture-uri "file://$@"
}

change_kde_wallpaper() {
    # I acknowledge the following is needlessly complicated and a usability
    # nightmare. Unfortunately there doesn't seem to be a patch for plasma
    # yet to make this more manageable from the command line

    # JS to send via dbus
    read -rd '' JS <<EOF
var allDesktops = desktops();
print (allDesktops);

for (i=0;i<allDesktops.length;i++) {
    d = allDesktops[i];
    d.wallpaperPlugin = "org.kde.image";
    d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");
    d.writeConfig("Image", "file://$@")
}
EOF

    # send JS to dbus to change wallpaper
    qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$JS" > /dev/null
}


if grep -q plasma <<< "$DESKTOP_SESSION"; then
    # KDE / Plasma
    change_kde_wallpaper "$@"
else
    # Gnome / MATE / Budgie
    change_gnome_wallpaper "$@"
fi
