#!/bin/bash

xset -b # no beep
nitrogen --restore &
pypanel &
~/bin/lemonlaunch &
~/bin/battmon &
pcmanfm -d &
urxvtd -o -q &
zim --plugin trayicon &
xautolock -detectsleep -time 3 -locker "/home/timothy/bin/screenlock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking screen in 30 seconds'" &

# run the following if we have an internet connection
~/.config/openbox/autostart-net &

# play a startup sound if it's not late
H=$(date +%H)
if (( 8 <= 10#$H && 10#$H < 21 )); then 
    ~/bin/volume -s half
    ~/bin/playalert startup
else
    ~/bin/volume -s mute
fi
