#!/bin/bash

for i in {1..3}; do
    NETSTATUS=$(~/bin/net-status > /dev/null)
    if [[ $NETSTATUS -eq 0 ]]; then
        aarchup -l 360 & # notify every 6 hours
        dropbox &
        pybitmessage &
        break;
    else
        sleep 5
    fi
done
